apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ${namespace}
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false