apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ${namespace}
  name: istio-operator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: false
    policy:
      enabled: false
    telemetry:
      enabled: false
    cni:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    